models.py
from datetime import datetime
from time import time
import re

from app import db


def slugify(s):
    pattern=r'[^\w+]'
    return re.sub(pattern,'-',s)

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140),unique=True)
    body=db.Column(db.Text)
    created = db.Column(db.DateTime,default=datetime.now())


    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        self.generate_slug()

        def generate_slug(self):
            if self.title:
                self.slug = slugify(self.title)
            else:
                self.slug = str(int(time()))

        def __repr__(self):
            return f'<Post id: {self.id}, title:{self.title}'
    
    

app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy


from  config import Config
from posts.blueprint import posts

app = Flask(__name__)
app.config.from_object(Config)



app.register_blueprint(posts, url_prefix='/blog')

db = SQLAlchemy(app)

main.py
from app import app
from app import db
import views


if __name__=='__main__':
    app.run() 

posts/blueprint.py
from flask import Blueprint
from flask import render_template


posts=Blueprint('posts', __name__,
                 template_folder='templates')


@posts.route('/')
def posts_list():
    return render_template('posts/posts.html')

views.py
from flask import render_template
from app import app


@app.route

@app.route('/')
def index():
    animal='Tiger'
    return render_template('index.html', name=animal)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width= , initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>
      {% block title %}

      {% endblock %}
    </title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{ url_for('index')}}">Flask</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{ url_for('posts.posts_list')}}">Blog</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

      <div class="container">
        <div class="row">
          <div class="col-8 mx-auto">
          {% block content %}

      {% endblock %}
     </div>
   
          
        </div>
      </div>
</body>
</html> 

templates/index.html
{% extends 'base.html'%}

{% block title %}
    Index page
      {% endblock %}


      {% block content %}
        <h1>Hello world from index.html</h1>
      {% endblock %}